### ISSUE TITLE
Talesandtails - teilweise falsche Preise + Barcode möglichst mit auslesen

### ISSUE THREAD

**Issue by VolkerSchroeder13** [MauriceLe/PIMS#51]
Lachs doch mal - Fisch Leckerli für Hunde mit Lachs
TL4611 - Einzeln - Preis 4,99 (aber in Datenbank mit 19,95) finde ich aber im source gar nicht....
TL2511 - 5er - Preis 24,95 passt
TL2101 - 10er - Preis 49,90 passt

Barcode sind im Source versteckt. möglichst mit auslesen.
TL4611 - 0784008546110

**Comment by finnbechinka** [comment]
So wies, aussieht haben die zwei Produkte mit der gleichen sku. 
Die 19,95 kommen nämlich hier her: [Lachs doch mal - Fisch Leckerli für Hunde mit Lachs (Reward)](https://talesandtails.de/products/lachs-doch-mal-reward?_pos=1&_sid=68eca7b2b&_ss=r).

**Comment by finnbechinka** [comment]
Das Produkt hat die tags "loyaltylion" und "reward".
Also das sieht für mich nach 'nem Bonusprogramm aus, bei dem man punkte, sammeln kann oder so und das Produkt dann kostenlos bekommt oder so.
Ich schließe erstmal Produkte mit den tags aus und aktuell ist es auch nur das eine.
