### ISSUE TITLE
Export - code anpassen

### ISSUE THREAD

**Issue by VolkerSchroeder13** [MauriceLe/PIMS#65]
hab noch mal mit dem Export gebastelt. mit ExcelWriter bekommen wir so eine korrekte Datei:

            with pd.ExcelWriter(file, engine='xlsxwriter', engine_kwargs={'options': {'encoding': 'utf-8'}}) as writer:excel.to_excel(writer, index=False)
 
Bitte in den Code einbauen bzw. ändern

**Comment by MauriceLe** [comment]
Wurde angepasst. Einmal ausprobieren!

**Comment by VolkerSchroeder13** [comment]
ich hab die items.py auch überarbeitet.

Hänge ich als Datei an.

Viele Grüße aus Bünde

Dipl.-Ing. Volker Schröder

PetVitalShop
Dipl.-Ing. Volker Schröder
Elsemühlenweg 85
32257 Bünde

Fon:  
+4952237944810

***@***.***
Homepage: www.petvitalshop.de

-----Ursprüngliche Daten-----
Datum: 07.07.2023 10:50:13
Von: Maurice Leenders ***@***.***>
An: MauriceLe/PIMS ***@***.***>
CC: VolkerSchroeder13 ***@***.***>, Author ***@***.***>
Betreff: Re: [MauriceLe/PIMS] Export - code anpassen (Issue #65)
Vorgang: T-YX58ODTWLF-14
